http:
  port: ':8081'
  host: 'localhost'
  read_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

env: 'development'

db:
  max_open_conns: 25
  max_idle_conns: 25
  max_idle_time: '15m'
  migration_path: 'migrations/pg'
  migration_version: 1

token:
  time_to_live: "15m"
